### PR TITLE
Allow to trigger CI 

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by matthiasnoback** [comment]
I don't understand what's wrong here, but I triggered the build :)

**Comment by TomasVotruba** [comment]
This PR should be just merged so the other PR is triggered automatically :)

**Comment by matthiasnoback** [comment]
Ah cool, sorry I misunderstood.

**Comment by TomasVotruba** [comment]
No troubles, it's a bit hacky way to use CI :P , thanks :+1:

**Pull request merged**
