### PR TITLE
Update to 2022 dependencies, so we can rebuild the book

### PR DESCRIPTION
**Pull request by TomasVotruba**
This is hopefully the last blocker for:
https://github.com/rectorphp/the-power-of-automated-refactoring/pull/189

Let's refresh :)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@matthiasnoback Hi Matthias, could you just trigger CI here? :)

Or even better, I've prepared a simple PR, so after merge it will allow me trigger CI by default:
https://github.com/matthiasnoback/leanpub-api-client/pull/7

**Comment by TomasVotruba** [comment]
Seems good to go :+1: :heavy_check_mark:

**Comment by matthiasnoback** [comment]
Ah great, thanks a lot!

**Comment by matthiasnoback** [comment]
Released as v1.2.3

**Comment by TomasVotruba** [comment]
Thank you 😊

**Comment by matthiasnoback** [comment]
No, thank you ;)

**Pull request merged**
